DELETE FROM LOGIN_USER_ATTRIBUTES;

INSERT INTO LOGIN_USER_ATTRIBUTES VALUES (1, 'ID-1の拡張属性1', 'ID-1の拡張属性2', 'ID-1の拡張属性3');
INSERT INTO LOGIN_USER_ATTRIBUTES VALUES (2, 'ID-2の拡張属性1', 'ID-2の拡張属性2', 'ID-2の拡張属性3');
INSERT INTO LOGIN_USER_ATTRIBUTES VALUES (3, 'ID-3の拡張属性1', 'ID-3の拡張属性2', 'ID-3の拡張属性3');
