DELETE FROM EMPLOYEE_ENTITY;

INSERT INTO EMPLOYEE_ENTITY VALUES (1, 'name1', 'dept1');
INSERT INTO EMPLOYEE_ENTITY VALUES (2, 'name2', 'dept2');
INSERT INTO EMPLOYEE_ENTITY VALUES (3, 'name3', 'dept3');
INSERT INTO EMPLOYEE_ENTITY VALUES (4, 'name4', 'dept4');
