CREATE SEQUENCE IF NOT EXISTS EMPLOYEE_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS EMPLOYEE_ENTITY (
    ID INT PRIMARY KEY,
    NAME VARCHAR(15),
    DEPT_NAME VARCHAR(15)
);
