CREATE SEQUENCE IF NOT EXISTS employee_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS employee (
    id INT generated by default as identity (START WITH 1000) PRIMARY KEY,
    name VARCHAR(15),
    dept_name VARCHAR(15)
);
