DELETE FROM PERSON_ENTITY;

INSERT INTO PERSON_ENTITY VALUES (1, 'name1');
INSERT INTO PERSON_ENTITY VALUES (2, 'name2');
INSERT INTO PERSON_ENTITY VALUES (3, 'name3');
INSERT INTO PERSON_ENTITY VALUES (4, 'name4');
